imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    sources:
      logging-bench:
        localFolder: .
    project: logging-bench/LoggingCrankBench.csproj 
    readyStateText: Application started.
    
scenarios:
  no-log:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5020
        path: /increment/no-log/99
  std-log:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5020
        path: /increment/std-log/99
  sourcegen-log:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5020
        path: /increment/sourcegen-log/99
  defined-log:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5020
        path: /increment/defined-log/99
  suppress-log:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5020
        path: /increment/suppress-log/99
        
profiles:
  local:
    variables:
      serverAddress: localhost
      ASPNETCORE_URLS: http://*:5020
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
